#!/usr/bin/env python3
"""Generate research.qmd from papers.yml.

Runs automatically before every Quarto render (see pre-render in _quarto.yml).
Never edit research.qmd by hand; edit papers.yml instead.
"""
import json
import pathlib
import re
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "papers.yml"
OUT = ROOT / "research.qmd"

SITE_URL = "https://ljubicageorgievska.github.io/webpage"
AUTHOR = {
    "@type": "Person",
    "name": "Ljubica Georgievska",
    "url": SITE_URL,
    "affiliation": [
        {"@type": "Organization",
         "name": "NYU Stern School of Business"},
        {"@type": "Organization",
         "name": "BI Norwegian Business School"},
    ],
}


def _plain(text: str) -> str:
    """Strip lightweight markdown (e.g. *(upcoming)*) for structured data."""
    text = re.sub(r"\*([^*]*)\*", r"\1", text or "")
    return re.sub(r"\s+", " ", text).strip()


def json_ld(papers: list) -> str:
    """schema.org JSON-LD describing every paper, read by search engines
    and by the AI research tools built on top of them."""
    graph = []
    for p in papers:
        entry = {
            "@type": "ScholarlyArticle",
            "headline": _plain(p.get("title", "")),
            "creativeWorkStatus": "Working paper",
            "author": [AUTHOR] + [
                {"@type": "Person", "name": c}
                for c in (p.get("coauthors") or [])
            ],
        }
        abstract = _plain(p.get("abstract", ""))
        if abstract:
            entry["abstract"] = abstract
        draft = (p.get("draft_url") or "").strip()
        pdf = (p.get("pdf") or "").strip()
        if draft:
            entry["url"] = draft
            entry["sameAs"] = draft
        elif pdf:
            entry["url"] = f"{SITE_URL}/papers/{pdf}"
        graph.append(entry)
    payload = {"@context": "https://schema.org", "@graph": graph}
    return ('<script type="application/ld+json">\n'
            + json.dumps(payload, indent=2, ensure_ascii=False)
            + "\n</script>")


def md_escape(text: str) -> str:
    """Trim and neutralise characters pandoc would misread (e.g. $ as math)."""
    return (text or "").strip().replace("$", "\\$")


def div(cls: str, content: str) -> str:
    """HTML tags on their own lines so pandoc parses the markdown inside."""
    return f'<div class="{cls}">\n{content}\n</div>'


def paper_block(p: dict) -> str:
    lines = []

    title = md_escape(p.get("title", "Untitled"))
    draft = (p.get("draft_url") or "").strip()
    pdf = (p.get("pdf") or "").strip()
    link = draft or (f"papers/{pdf}" if pdf else "")
    shown_title = f"[{title}]({link})" if link else title
    badge = '<span class="badge-new">New</span>' if p.get("new") else ""
    number = p.get("number")
    prefix = f"{number}\\. " if number is not None else ""

    coauthors = p.get("coauthors") or []
    coauthor_span = ""
    if coauthors:
        if len(coauthors) == 1:
            joined = coauthors[0]
        else:
            joined = ", ".join(coauthors[:-1]) + " and " + coauthors[-1]
        coauthor_span = f' <span class="title-coauthors">- with {joined}</span>'
    lines.append(div("paper-title",
                     f"{badge}{prefix}{shown_title}{coauthor_span}"))

    note = md_escape(p.get("note", ""))
    if note:
        lines.append(div("paper-note", f"({note.rstrip('.')})"))

    awards = md_escape(p.get("awards", ""))
    if awards:
        lines.append(div("awards", awards))

    pres = md_escape(p.get("presentations", ""))
    if pres:
        lines.append(
            '<details class="presentations">\n<summary>Presentations</summary>\n\n'
            f"{pres}\n\n</details>"
        )

    abstract = md_escape(p.get("abstract", ""))
    if abstract:
        label = p.get("abstract_label", "Abstract")
        lines.append(
            f'<details class="abstract">\n<summary>{label}</summary>\n\n'
            f"{abstract}\n\n</details>"
        )

    links = []
    if draft:
        links.append(f"[[Updated draft]]({draft})")
    if pdf:
        links.append(f"[[PDF]](papers/{pdf})")
    appendix_url = (p.get("appendix_url") or "").strip()
    appendix_pdf = (p.get("appendix_pdf") or "").strip()
    if appendix_url:
        links.append(f"[[Internet Appendix]]({appendix_url})")
    elif appendix_pdf:
        links.append(f"[[Internet Appendix]](papers/{appendix_pdf})")
    for extra in p.get("extra_links") or []:
        links.append(f"[[{extra['text']}]]({extra['url']})")
    if links:
        lines.append(div("paper-links", " ".join(links)))

    return "\n\n".join(lines)


def main() -> None:
    data = yaml.safe_load(DATA.read_text(encoding="utf-8"))
    papers = data.get("working_papers") or []
    papers.sort(key=lambda p: p.get("number") or 0, reverse=True)

    parts = [
        "---",
        'title: "Research"',
        "toc: false",
        "---",
        "",
        "<!-- AUTO-GENERATED from papers.yml. Do not edit this file:",
        "     edit papers.yml instead; this page is rebuilt on every deploy. -->",
        "",
        "## Working Papers",
        "",
    ]
    parts.extend(paper_block(p) + "\n" for p in papers)

    pubs = data.get("publications") or []
    if pubs:
        parts.append("## Publications")
        parts.append("")
        for pub in pubs:
            parts.append(div("pub-citation", md_escape(pub.get("citation", ""))))
            parts.append("")

    # Invisible structured data for search engines and AI research tools.
    parts.append(json_ld(papers))
    parts.append("")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} with {len(papers)} working papers and {len(pubs)} publications.")


if __name__ == "__main__":
    main()
