#!/usr/bin/env python3
"""Generate research.qmd from papers.yml.

Runs automatically before every Quarto render (see pre-render in _quarto.yml).
Never edit research.qmd by hand; edit papers.yml instead.
"""
import pathlib
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "papers.yml"
OUT = ROOT / "research.qmd"


def md_escape(text: str) -> str:
    """Trim and neutralise characters pandoc would misread (e.g. $ as math)."""
    return (text or "").strip().replace("$", "\\$")


def div(cls: str, content: str) -> str:
    """HTML tags on their own lines so pandoc parses the markdown inside."""
    return f'<div class="{cls}">\n{content}\n</div>'


def paper_block(p: dict) -> str:
    lines = []

    title = md_escape(p.get("title", "Untitled"))
    draft = (p.get("draft_url") or "").strip()
    pdf = (p.get("pdf") or "").strip()
    link = draft or (f"papers/{pdf}" if pdf else "")
    shown_title = f"[{title}]({link})" if link else title
    badge = ' <span class="badge-new">New</span>' if p.get("new") else ""
    number = p.get("number")
    prefix = f"{number}\\. " if number is not None else ""
    lines.append(div("paper-title", f"{prefix}{shown_title}{badge}"))

    coauthors = p.get("coauthors") or []
    if coauthors:
        if len(coauthors) == 1:
            joined = coauthors[0]
        else:
            joined = ", ".join(coauthors[:-1]) + " and " + coauthors[-1]
        lines.append(div("coauthors", f"with {joined}"))

    note = md_escape(p.get("note", ""))
    if note:
        lines.append(div("paper-note", f"({note.rstrip('.')})"))

    awards = md_escape(p.get("awards", ""))
    if awards:
        lines.append(div("awards", awards))

    pres = md_escape(p.get("presentations", ""))
    if pres:
        lines.append(
            '<details class="presentations">\n<summary>Presentations</summary>\n\n'
            f"{pres}\n\n</details>"
        )

    abstract = md_escape(p.get("abstract", ""))
    if abstract:
        label = p.get("abstract_label", "Abstract")
        lines.append(
            f'<details class="abstract">\n<summary>{label}</summary>\n\n'
            f"{abstract}\n\n</details>"
        )

    links = []
    if draft:
        links.append(f"[[Updated draft]]({draft})")
    if pdf:
        links.append(f"[[PDF]](papers/{pdf})")
    appendix_url = (p.get("appendix_url") or "").strip()
    appendix_pdf = (p.get("appendix_pdf") or "").strip()
    if appendix_url:
        links.append(f"[[Internet Appendix]]({appendix_url})")
    elif appendix_pdf:
        links.append(f"[[Internet Appendix]](papers/{appendix_pdf})")
    for extra in p.get("extra_links") or []:
        links.append(f"[[{extra['text']}]]({extra['url']})")
    if links:
        lines.append(div("paper-links", " ".join(links)))

    return "\n\n".join(lines)


def main() -> None:
    data = yaml.safe_load(DATA.read_text(encoding="utf-8"))
    papers = data.get("working_papers") or []
    papers.sort(key=lambda p: p.get("number") or 0, reverse=True)

    parts = [
        "---",
        'title: "Research"',
        "toc: false",
        "---",
        "",
        "<!-- AUTO-GENERATED from papers.yml. Do not edit this file:",
        "     edit papers.yml instead; this page is rebuilt on every deploy. -->",
        "",
        "## Working Papers",
        "",
    ]
    parts.extend(paper_block(p) + "\n" for p in papers)

    pubs = data.get("publications") or []
    if pubs:
        parts.append("## Publications")
        parts.append("")
        for pub in pubs:
            parts.append(md_escape(pub.get("citation", "")))
            parts.append("")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} with {len(papers)} working papers and {len(pubs)} publications.")


if __name__ == "__main__":
    main()
